// client/js/Pages/Home.jsx
import React from 'react';
import { Link } from '@inertiajs/inertia-react';

export default function Home(props) {
    return (<div>
        <h1>{ props.message }</h1>
        <Link href="/contact">Contact</Link>

        <p>You can mix Inertia with traditional routed pages (normal non-react links)</p>
        <a href="/non-inertia-view">Non-Inertia View</a>
    </div>)
};

// assets/js/Pages/Home.vue
<template>
  <h1>Home Page</h1>

  <h2>{{ message }}</h2>

  <Link :href="`/contact`">Contact</Link>

  <Link :href="`/invalid`">404</Link>
</template>

<script>
  import { Link } from '@inertiajs/inertia-vue3'
  export default {
    components: {
      Link
    },
    props: {
      message: ''
    }
  }
</script>
